---
title: "functions"
format: html
---
```{r}
library(roxygen2)
```

```{r}
airtemps = c(212, 30.3, 78, 32)
celsius1 = (airtemps[1]-32)*(5/9)
celsius2 = (airtemps[2]-32)*(5/9)
celsius3 = (airtemps[3]-32)*(5/9)
celsius4 = (airtemps[4]-32)*(5/9)

```

```{r}
#' Convert temp from F to celcius
#' 
#' @param x temperature in degrees F
#' @return temperature in degrees C
#' @export
#' @examples 
#' farh_2_celcius(32)
farh_2_celcius = function(x){
  celsius = (x-32)*(5/9)
  return(celsius)
}
```

```{r}
farh = farh_2_celcius(airtemps)
```

```{r}
celcius_2_farh = function(x){
  farh = (x/(5/9))+32
  return(farh)
}

celcius_2_farh(farh)
```

```{r}
airtemps == celcius_2_farh(farh)
```
## Explorinhg time saving functions
```{r}
convert_temps = function(farh){
  celcius = (farh-30)*(5/9)
  kelvin = celcius + 273.15
  return(list(farh = farh, celcius = celcius, kelvin = kelvin))
}

temps_df = data.frame(convert_temps(seq(-100, 100, 10)))
```


## ggplot custom themes
```{r}
custom_theme = function(base_size = 9){
  ggplot2::theme(
    text = ggplot2::element_text(family='Helvetica', color='gray30', size=base_size),
    plot.title = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold')
  )
}
```

```{r}
library(ggplot2)
ggplot(temps_df, aes(x = farh, y = celcius, color = kelvin))+
  geom_point()+
  custom_theme()+
  labs(title="Temperatures")
```

## Scatterplot function
```{r}
scatterplot = function(df, point_size = 2, font_size = 16){
  ggplot(df, aes(x = farh, y = celcius, color = kelvin))+
    geom_point(size = point_size)+
    custom_theme(font_size)
}

scatterplot(temps_df, point_size = 3, font_size = 14)
```











